# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: "Bruno Vicco"
email: "bfvicco@gmail.com"
description: >
  Building bridges between business and technology with Generative AI.
  Specializing in LLMs, RAG, and Conversational Agents to solve complex challenges.
repository: "brunovicco/brunovicco.github.io"
github_username: "bfvicco"
url: "https://brunovicco.github.io"
minimal_mistakes_skin: "air"
search: true

# Build settings
markdown: kramdown
#remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"
timezone: America/Sao_Paulo

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Bruno Vicco"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Software Engineer (GenAI) @ Itaú Unibanco. Passionate about LLMs, RAG, and translating complex problems into impactful solutions."
  location: "São Paulo, Brazil"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/brunovicco/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brunovicco"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:bfvicco@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/brunovicco/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brunovicco"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages (inglês)
  - scope:
      path: "_pages/en"
      type: pages
    values:
      layout: single
      author_profile: true
      lang: en
  # _pages (português)
  - scope:
      path: "_pages/pt"
      type: pages
    values:
      layout: single
      author_profile: true
      lang: pt

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
